name: Build and Publish image to Docker Hub

on:
  [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build ./api/ -t rushikesh611/devops-qr-code-api:latest

      - name: Push Docker image
        run: |
          docker push rushikesh611/devops-qr-code-api:latest